config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  resources :books, only: [:edit, :create, :index, :show, :destroy, :update]
  resources :users, only: [:edit, :create, :index, :show, :update]
  get "home/about" => "homes#about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def edit
    @book=Book.find(params[:id])
    @user=@book.user
    if @user == current_user
    else
      redirect_to books_path
    end
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book)
    else
      @books= Book.all
     render :index
    end
  end

  def index
    @bookers =Book.new
    @books= Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @bookers =Book.new
    @book =Book.find(params[:id])
    @user = @book.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to @book
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :caption)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :authenticate_user!,except: [:top, :about]

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @bookers =Book.new
    @users = User.all
    @user = current_user

  end

  def show
    @bookers =Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user= User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <div id='error_explanation'>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:<% end %></h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li>
            <%= message %><% end %>
          </li>
        </ul>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <div class="field_with_errors">
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <div class="field_with_errors">
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", "/books/#{@book.id}" %>
      |
      <%= link_to "Back", "/books" %>
    </div>
  </div>
</div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id='error_explanation'>
  <h3><%= @book.errors.count %>error prohibited this obj from being saved:<% end %></h3>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %><% end %></li>
    </ul>
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'users/list', user:@user, bookers:@bookers %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opnion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |books| %>
      <tr>
        <td>
          <%= link_to user_path(books.user) do %>
          <%= attachment_image_tag books.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
          <% end %>
          </td>
        <td><%= link_to books.title, "/books/#{books.id}" %></td>
        <td><%= books.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'users/list', user:@user, bookers:@bookers %>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@book.user) do %>
          <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to user_path(@book.user) do %>
          <%= @book.title %>
          <% end %>
          </td>
        <td><%= @book.body %></td>
        <% if current_user == @book.user %>
        <td>
          <%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
        <td>
            <%= link_to "Destroy", "/books/#{@book.id}" ,method: :delete, data: { confirm: "本当に消しますか？"}, class:"btn btn-danger"  %>
        </td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers !</strong>
        </h1>
   </div>
  </div>
</div>

app/views/homes/top.html.erb
<main>
 <div class="container">
  <div class="row">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <script src="https://kit.fontawesome.com/ee99b9e03b.js" crossorigin="anonymous"></script>
  <h1>
   welcome to
   <i class="fas fa-book"></i>
   <strong>Bookers !!</strong>
  </h1>
   <p>
     In
     <i class="fas fa-book"></i>
     <strong>Bookers</strong>
   </p>
   <p>you can share and exchange your opinions , inpressions , and emotions</p>
   <p>about various books!</p>

   <a href="/users/sign_in" class="btn btn-info btn-sm btn-block mb-3 sign_in">Log in</a>
   <a href="/users/sign_up" class="btn btn-success btn-sm btn-block sign_up" >Sign Up</a>
   </div>
  </div>
 </div>


 </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<script src="https://kit.fontawesome.com/ee99b9e03b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class=" navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to 'Home', user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to 'Users', '/users', class: 'fas fa-users nav-link text-light' %>
            </li>
            <li>
              <%= link_to 'Books', books_path, class:'fas fa-book-open nav-link text-light' %>
            </li>
            <li>
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            <% else %>
            <li>
              <%= link_to 'Home', root_path, class:'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to 'About', home_about_path, class:'fas fa-link nav-link text-light' %>
            </li>
            <li>
              <%= link_to "sign up", new_user_registration_path, class:'fas fa-user-plus nav-link text-light' %>
            </li>
            <li>
              <%= link_to "login", new_user_session_path, class:'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
     <tbody>
      <tr>
       <th>name</th>
       <th class="profile-name"><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th class="profile-introduction"><%= user.introduction %></th>
      </tr>
     </tbody>
    </table>
    <%= link_to "",edit_user_path(user[:id]),class: "btn btn-outline-secondary btn-block fas fa-user-cog"  %>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: @bookers, local:true do |f| %>
    <div class="form-group">
     <label for="book_title">Title</label>
     <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
     <label for="book_body">Opinion</label>
     <%= f.text_area :body, class:"form-control" %>
    </div>
    <div class="book_new">
     <%= f.submit 'Create Book', class:"btn btn-success" %>
    </div>
   </div>
   <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
      <div id='error_explanation'>
       <h3><%= @user.errors.count %>error prohibited this obj from being saved:<% end %></h3>
       <ul>
         <% @user.errors.full_messages.each do |message| %>
         <li>
           <%= message %>
           <% end %>
         </li>
       </ul>
      </div>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="user-name">Name</label>
        <div class="field_with_errors">
          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName"%>
      　</div>
      </div>
      <div class="form-group">
        <label for="user_image">image</label>
        <div class="form-control-file user_image">
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
      </div>
      <div class="form-group">
        <ladbl fol="user_introduction">introduction</ladbl>
      <div class="introduction">
        <%= f.text_area :introduction, class:"form-control" %>
      </div>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <%= render 'users/list', user:@user, bookers:@bookers %>
 <div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opnion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |books| %>
          <tr>
            <td>
              <%= link_to user_path(books.user) do %>
          <%= attachment_image_tag books.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
          <% end %>
            </td>
            <td><%= link_to books.title, "/books/#{books.id}" %></td>
            <td><%= books.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>